gyscos/zstd-rs

src/stream/decoder.rs, src/stream/mod.rs
Do not suppose end-of-frame is aligned with storage's end-of-file.
Handy when zstd frames are part of larger streams, used to return
some puzzling "Context should be init first" error.
Zstd natively recognizes frame termination and signal the situation
through the special `0` value of the returned variant:
"ZBUFF_decompressContinue returns either a hint to preferred nb
of bytes to use as input for next function call or 0 when a frame
is completely decoded, or an error code, which can be tested using
ZBUFF_isError()".
Closes #3.
=> fix: end-of-frame detection.

src/stream/decoder.rs, src/stream/encoder.rs
These turn out to be useful when inspecting or poking at the wrapped stream's internal state.
=> stream: add get_ref and get_mut to encoder and decoder types

src/stream/encoder.rs, src/stream/mod.rs
The problem here was that the buffer could still have some data in it at the
time it is overwritten. This would cause corruption, demonstrated by the
tests if run without the corresponding code changes.
None of the existing tests tested partial writes at all. To test this,
generalize `WriteWithReject` to also handle partial writes.
=> encoder: write out buffer before starting flush or finish

src/stream/encoder.rs
While `Interrupted` is theoretically a valid thing to return here, many
consumers deal poorly with it. It's much easier both for us and for consumers
to just loop until the internal buffer has been completely written out.
Other encoders like `bzip2-rs` and `flate2-rs` do the same thing.
=> encoder: avoid returning ErrorKind::Interrupted

Cargo.toml, src/dict.rs, src/lib.rs, src/stream/decoder.rs, src/stream/encoder.rs, src/stream/mod.rs
We recently released the `partial-io` crate, which adds convenience wrappers
for partial reads and writes.  It's basically a more formal version of a couple
of helpers we already had.
`partial-io` also supports `quickcheck` for random test cases. That could
eventually be used as well, as in e.g.
https://github.com/alexcrichton/bzip2-rs/pull/20.
What do you think?
=> use partial-io for I/O tests

.travis.yml
This makes sure the project builds both with tokio and without.
=> travis: add CI for the optional tokio feature

Cargo.toml, src/lib.rs, src/stream/decoder.rs, src/stream/encoder.rs
This is pretty straightforward and a good demonstration that zstd
doesn't break down when confronted with transient errors.
=> stream: switch to randomized testing with partial-io

src/block/compressor.rs, src/block/decompressor.rs, src/stream/decoder.rs, src/stream/encoder.rs, zstd-safe/src/lib.rs
According to @Cyan4973, streams and contexts support `Send`, and dicts
support both `Send` and `Sync`.
Also include compile-time checks to make sure the higher-level stream and block APIs support `Send`.
=> Make zstd contexts and streams support Send, and dicts support Send + Sync

zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs
The `hide_type` method has been renamed to `blacklist_type` to match the CLI flag.
The bindings seem to work just fine with `generate_comments` for me now.
=> Update `bindgen` dependency to 0.31.X

zstd-safe/src/lib.rs
Unfortunately it's a public method, so should probably be a semver bump to release.
=> typo in pub method name (create-ddict)

zstd-safe/zstd-sys/build.rs
Deprecated methods are not used in zstd-safe, so it is not necessary to build it
=> Do not build ZSTD deprecated features

src/dict.rs, src/stream/decoder.rs, src/stream/encoder.rs
Prepared dictionaries are much faster when processing multiple streams with same dictionary, especially for short streams with low compression level.
Stream of 196 bytes compressed with level 1:
```
test tests::bench_with_dictionary              ... bench:      21,634 ns/iter (+/- 9,484)
test tests::bench_with_prepared_dictionary     ... bench:       4,703 ns/iter (+/- 3,200)
```
Fixes #17
=> Support for prepared dictionaries for stream Encoder and Decoder

zstd-safe/src/lib.rs, zstd-safe/zstd-sys/build.rs, zstd-safe/zstd-sys/src/bindings.rs
I started writing a safe wrapper for `ZSTD_CCtx_setParameter`, which would allow users of the lower level API to work around #37. I've suddenly realised it probably doesn't actually help me for my code, though, so I stopped. Maybe I'll start again when I realise I've made a mistake.
Compiles, doesn't break any tests, but isn't run by any tests.
Hopefully it will be useful for someone.
=> Partial safe wrapper for ZSTD_CCtx_setParameter

src/block/compressor.rs, src/block/decompressor.rs, src/dict.rs, src/lib.rs, src/stream/raw.rs, src/stream/read/tests.rs, zstd-safe/src/lib.rs
One part of being safe is to check error codes. But current implementation always return usize and return code must be checked in zstd-rs crate. This commit changes the behaviour that zstd-safe functions returns SafeResult.
=> Make zstd_safe really safe

zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs, zstd-safe/zstd-sys/zstd.h
This will use pkg-config to locate the existing library. Use in
combination with bindgen to generate a binding from that header.
The `non-cargo` feature will suppress emitting metadata for cargo
(for cases where cargo isn't doing the final link).
Addresses issue https://github.com/gyscos/zstd-rs/issues/58
=> Add pkg-config feature to use pre-installed libzstd

zstd-safe/zstd-sys/build.rs
The common/zstd_errors.h header file is also part of the public
interface of the zstd library. Copy it into the output directory, like
the upstream build system does [0], so that downstream dependencies can
find it.
[0]: https://github.com/facebook/zstd/blob/0f9866add2df8e824c96f67fc49a7d5b69ad3317/lib/Makefile#L275
=> Copy public zstd_errors.h into output directory

zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs
Depending projects will be able to use this by looking into the env
varilabe `DEP_ZSTD_INCLUDE`. This variable will contain a `;` seperated
list of include paths.
=> Export includes paths as cargo metadata

zstd-safe/zstd-sys/build.rs
Advanced features like multithreading are only available when libzstd
is statically linked per documentation. pkg-config is not very good
for static linking. That means users have to rely on this crate to build it
correctly.
Current `build.rs` is not passing `ZSTD_MULTITHREAD` flag to cc and
because of that resulting library built without multithreading support.
Resolves: #64
=> fix: Set ZSTD_MULTITHREAD when built with zstdmt

zstd-safe/zstd-sys/build.rs, zstd-safe/zstd-sys/src/bindings_experimental.rs, zstd-safe/zstd-sys/src/bindings_std_experimental.rs, zstd-safe/zstd-sys/update_bindings.sh
dictBuilder/zdict.h contains additional experimental zstd APIs.
This includes low-level APIs for training dictionaries with full
control over parameters.
I need access to these APIs in order to implement a Rust backend
for my Python bindings to zstandard project
(https://github.com/indygreg/python-zstandard).
For reasons unknown to me, the dictionary experimenting APIs are
gated behind a separate preprocessor define. Simply adding this
define is enough to cause the bindings to be generated.
=> Generate experimental dictionary bindings

zstd-safe/Cargo.toml, zstd-safe/build.rs, zstd-safe/src/lib.rs, zstd-safe/zstd-sys/build.rs
Beside wasm32 also RustHermit doen't have a classical C library.
Using of target_arch/_os to detect these platforms. It simplifies
the usage of this crate.
=> using of target_arch/_os to detect, if the platform has a libc

zstd-safe/zstd-sys/Cargo.toml
This bindgen update does not require other code changes, as far as I can tell. A local build of zstd-sys with bindgen 0.56 was successful.
=> Update bindgen to 0.56

src/stream/mod.rs, src/stream/read/mod.rs, src/stream/write/mod.rs
adds configurability of the following:
* dictid inclusion (saves 4 bytes when using dicts)
* include_magicbytes (saves 4 bytes always)
* include_contentsize (unsure)
Fixes #37 .
=> add more config functions for better compression for small data

Cargo.toml, zstd-safe/Cargo.toml, zstd-safe/zstd-sys/build.rs
ZSTD sometimes doesn't output very helpful information by default. This adds a feature to enable debug logging from zstd.
before:
```
[2020-12-20T16:16:04Z DEBUG sqlite_zstd::dict_training] training dict of size 1503kB with 196608 samples of total size 150338kB (of 196608 samples seen)
Error: Training dictionary failed
Caused by:
Error (generic)
```
what is happen??!!
after with features = ["debug"]:
```
[2020-12-20T16:16:04Z DEBUG sqlite_zstd::dict_training] training dict of size 1503kB with 196608 samples of total size 150338kB (of 196608 samples seen)
zstd/lib/dictBuilder/zdict.c: ZDICT_trainFromBuffer
Trying 5 different sets of parameters
d=8
Training on 147456 samples of total size 100940410
Testing on 49152 samples of total size 49397760
Computing frequencies
k=50
Breaking content …
```
=> add debug feature to enable zstd debug logs

src/lib.rs
Should be straightforward. The reason for adding `impl Debug` is so that in my program I can easily print the accepted range if the user passes an out-of-bounds value.
=> Expose the accepted range of compression levels.

src/block/decompressor.rs, zstd-safe/src/lib.rs, zstd-safe/src/tests.rs
There's an experimental API that gives us an upper limit on the space needed to decompress a given zstd compressed block. 
Expose this to users if the `experimental` feature is on and the block is valid, and use it in `decompress` to reduce the size of allocations if the C library promises that decompressed data is smaller than the capacity the user provided.
Without `experimental`, we always return `None` for the upper bound, which is treated by the `decompress` changes as "do not limit capacity".
=> Use decompression bound API to limit decompressor allocation

zstd-safe/zstd-sys/Cargo.toml
I happened to be watching the output of a fresh fetch and noticed that zstd-sys was the largest crate that was downloaded at 1.9MiB and suspected it was due to including the entirety of the C lib's repo, which was indeed the case. This just excludes everything from that repo that isn't needed for actually compiling the lib, and the the LICENSE/COPYING file of course.
This makes the crate go from 1.9MiB to 632KiB, so a little less than 1/3 of the current size.
=> Exclude unneeded files from the C repo when packaging

src/stream/mod.rs
zstd 1.3.2 added a long-distance matcher
(https://github.com/facebook/zstd/releases/tag/v1.3.2); add a function
to set that parameter.
=> Support the new long-distance matcher

src/stream/zio/reader.rs
This is done by first asking zstd for more data, before trying to read
more compressed bytes from the data source.
An alternative would be the
[`BufReader::buffer`](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.buffer)
function, but that is not available because we only have a type that
satisfies `BufRead` in this context.
I tested this with my TCP connection and it solved my problem.
Fixes #119.
I haven't tested this for performance regressions.
=> Fix the Decoder API sometimes not outputting all available data

zstd-safe/zstd-sys/Cargo.toml
Using `cargo vendor` with `zstd-sys` does not copy the `zstd` directory, due to a bug in Cargo: https://github.com/rust-lang/cargo/issues/9555
This commit replaces the "exclude" field with a negation, which causes an issue with current version of Cargo, by an equivalent
"include" field.
=> Cargo bug workaround

src/stream/write/mod.rs
Explaining how to create the `AutoFinishEncoder` from the `Encoder`.
Closes #129.
=> Improve documentation of AutoFinishEncoder

Cargo.toml, examples/train.rs, src/dict.rs, zstd-safe/Cargo.toml, zstd-safe/src/lib.rs, zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs, zstd-safe/zstd-sys/examples/it_work.rs, zstd-safe/zstd-sys/src/lib.rs, zstd-safe/zstd-sys/src/wasm_shim.rs, zstd-safe/zstd-sys/wasm-shim/stdlib.h, zstd-safe/zstd-sys/wasm-shim/string.h
This PR adds a simple wasm shim to `zstd-sys` to support `wasm32-unknown-unknown` arch.
The `legacy` and `dict_builder` cannot be compiled on this shim because they depend on `stdio.h`, so I added a new feature cfg to turning off `dict_builder` code.
You can test it with `wasmtime`
```
> cd zstd-safe/zstd-sys/
> cargo build --target wasm32-unknown-unknown --no-default-features --example it_work
> wasmtime target/wasm32-unknown-unknown/debug/examples/it_work.wasm --invoke test_compress
```
=> zstd-sys: impl wasm32-unknown-unknown support

zstd-safe/zstd-sys/Cargo.toml
Building the released `0.11` does not work for `wasm32-unknown-unknown`, while the build does work for the same revision from Git. 
In the process of making an example (https://github.com/kylebarron/zstd-rs-wasm-bug-example), I realized the shim files were likely not included in the release. `cargo package --list` in `zstd-sys` confirmed that previously the `wasm-shim` files were not included in the build.
=> Include wasm-shim files in cargo package

zstd-safe/zstd-sys/build.rs
Fat LTO usually can reduce binary size while improving the performance.
Thin LTO does the same, but taking less time.
Signed-off-by: Jiahao XU [Jiahao_XU@outlook.com](mailto:Jiahao_XU@outlook.com)
=> Unconditionally enable thin LTO in for `zstd-sys`

zstd-safe/zstd-sys/Cargo.toml
`bindgen` enables feature "clap" and "logging" by default, which is used only in binary but not in library.
=> Disable unused features of dep `bindgen`

zstd-safe/zstd-sys/build.rs
This is to make the build more deterministic.
Note that `fs::read_dir()`'s behavior is platform-specific. We sort the
returned result of `read_dir` to make the file addition order
deterministic.
=> Deterministic file adding order in compile_zstd()

zstd-safe/zstd-sys/build.rs
This issue got exposed with [CC upgrading to 1.0.77] and now detecting the `.S` file extension to pass on to `ml64.exe` (MASM) on Windows; we don't have that on our cross-compiling (from Linux to Windows) CI setup, hence uncovered that this build script was using the _`target_os` flag from the host_ in the build script to make a decision on _what to compile for the target_.
[CC upgrading to 1.0.77]: https://github.com/rust-lang/cc-rs/compare/1.0.76...1.0.77
---
Curiously this implies the `.S` file must have compiled fine for us on `cc 1.0.76` and prior, or somehow got skipped (expecting errors when `ZSTD_DISABLE_ASM` isn't defined...).
=> zstd-sys: Don't use `target*` cfg in `build.rs` to fix Windows cross-compile

zstd-safe/zstd-sys/build.rs
=> Improve zstd-sys/build.rs: Fallback to `-Os` or `-O2` if `-Oz` is not supported

zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs
fixes #150 
this makes pkg-config a non-optional build-dependency
now having `ZSTD_SYS_USE_PKG_CONFIG` will be equivalent to having the pkg-config feature
=> add environment variable to force usage of pkg-config

zstd-safe/zstd-sys/build.rs
This PR enables building with the `wasm32-wasi` target by using the same shims that are used for the `wasm32-unknown-unknown` target.
Both of the following commands run successfully
```
cargo build  --target wasm32-unknown-unknown --no-default-features
cargo build  --target wasm32-wasi --no-default-features
```
=> Add support for `wasm32-wasi`

zstd-safe/zstd-sys/build.rs
Rm unused function/data, merge constants and use icf=safe to safely
merge identical functions.
=> Optimize zstd-sys vendered build

zstd-safe/zstd-sys/build.rs
=> Fix `main` in `zstd-sys` `build.rs`: Use `var_os` for `CARGO_MANIFEST_DIR`

zstd-safe/zstd-sys/build.rs
Use iterator-style loop instead of for-loop while also reducing size of the `entries: Vec<_>` by filtering out unwanted `entry` before `collect`ing into a `Vec<_>`.
Also, use `Build::files` instead of `Build::file` to avoid the for-loop.
=> refactor `*.c` files discovery in `compile_zstd`

zstd-safe/zstd-sys/build.rs
- accept any `&dyn fmt::Display`
- avoid dup `cargo:` prefix in `content`
- avoid error caused by `cfg`
=> Refactor and optimize `cargo_print`

zstd-safe/zstd-sys/build.rs
since `ZSTD_LIB_MINIFY` is only used in `Makefile` to enable other `#define`s.
Fixed bug introduced in #189 and in pointed out by @nickbabcock in https://github.com/gyscos/zstd-rs/issues/190#issuecomment-1405126770
=> Fix zstd-sys in thin mode: Replace `ZSTD_LIB_MINIFY` with actual `#define`s

Cargo.toml, zstd-safe/Cargo.toml, zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/build.rs
- fat-lto for fat lto, will override thin-lto if specified
- thin-lto for thin lto, will fallback to fat-lto is not supported
=> Re-enable lto support guarded behind feature flags

zstd-safe/zstd-sys/build.rs
Prevoiusly, we filter based on `entry.path()`, which includes the full path.
But the filtering rules only care about the filename, hence we use `entry.file_name()` here and group two `filter` into one `filter_map`.
=> Optimize `compile_zstd` for-loop in zstd-sys build.rs

zstd-safe/zstd-sys/build.rs
This PR disables wasm-shim for wasm32-unknown-emscripten, which provides its own stdlib.h and string.h so does not need wasm-shim.
Without this PR, running `cargo build --target wasm32-unknown-emscripten` fails for zstd-sys:
```
cargo:warning=zstd/lib/dictBuilder/cover.c:262:10: error: call to undeclared library function 'memcmp' with type 'int (const void *, const void *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
cargo:warning=  return memcmp(ctx->samples + lhs, ctx->samples + rhs, ctx->d);
cargo:warning=         ^
cargo:warning=zstd/lib/dictBuilder/cover.c:262:10: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
cargo:warning=zstd/lib/dictBuilder/cover.c:629:5: error: call to …
```
=> Fix zstd-sys for wasm32-unknown-emscripten

zstd-safe/src/lib.rs
Changes the invariant for the `around_pos()` constructor to not panic when the valid case of constructing an empty `OutBuf`. This constructor was inconsistent with the documentation for the struct and the `set_pos()` method. [Zstd documentation](https://github.com/facebook/zstd/blob/95ffc767f62e8aaeba363af49a590f8662cc2465/lib/zstd.h#L670) also confirms that empty buffer is a valid use case.
Fixes #214
=> Fix OutBuf around_pos invariant

zstd-safe/Cargo.toml
Merging and publishing would allow #215 to be fixed. If there are other changes maybe this needs to be a minor bump.
=> Bump zstd-safe patch version

zstd-safe/Cargo.toml, zstd-safe/src/lib.rs, zstd-safe/zstd-sys/Cargo.toml, zstd-safe/zstd-sys/src/bindings_zdict.rs, zstd-safe/zstd-sys/src/bindings_zdict_experimental.rs, zstd-safe/zstd-sys/src/bindings_zstd.rs, zstd-safe/zstd-sys/src/bindings_zstd_experimental.rs
I do not know if there is any technical reason why this would be a bad idea, but I propose swapping all uses of libc in `zstd-safe` and `zstd-sys` with `core::ffi` in order to support targets which do not fully support libc, such as `aarch64-nintendo-switch-freestanding`.
=> Swap libc to `core::ffi`

src/stream/raw.rs, zstd-safe/src/lib.rs
I was auditing the zstd crate's usage of unsafe blocks as part of a larger effort to audit the transitive dependencies of Wasmtime. I haven't audited zstd_safe in detail, but I believe the following two issues are the only ones which impact the few `unsafe` blocks in the zstd crate. Hopefully I'll have time later to go look at zstd_safe in depth as well.
Issue 1:
When `zstd::stream::raw::NoOp::run` computes the length of the slice that it should copy, it does not take `output.pos()` into account. Instead it can write up to offset `output.dst.capacity() + output.pos()`, if the input is long enough. So even someone who uses NoOp exactly as it's intended to be used may trigger a buffer overrun.
The minimal fix for this issue is to use `output.dst.capacity() - output.pos()` instead, in the …
=> Fix two buffer overruns reachable from safe code

.github/workflows/wasm.yml, zstd-safe/zstd-sys/build.rs
`XXH_STATIC_ASSERT` appears to already have a reasonable definition, and defining it to `0` breaks uses of it.
I'm not sure why that definition was added originally.
This also fixes the github action workflow to actually build the wasm target; previously it was just building the native target which allowed this issue to slip through.
Fixes #271.
=> Fix wasm32-unknown-unknown support

zstd-safe/src/lib.rs
Create a safe `ThreadPool` type wrapping `ZSTD_threadPool`. Allow binding a `&ThreadPool` to a `CCtx`, which requires that the lifetime of the `&ThreadPool` outlive the `CCtx`.
Fixes: #282
=> Support thread pools

src/stream/read/mod.rs
Rust structs with generic type parameters are typically not declared with trait bounds on the struct itself, as this makes it difficult to compose into other generic structs. The `zip` crate depends on `zstd`, and is unable to declare a generic `ZipFileReader` enum (e.g. https://github.com/zip-rs/zip2/blob/b6e0a0693ba2d07f541cd9017b60df7e65817e48/src/read.rs#L190) without creating a vtable `&'a mut dyn Read`, since the `R: BufRead` bound on the `Decoder` struct declaration requires a concrete type implementing `BufRead`, whereas `io::BufReader` doesn't have the same `R: Read` bound on the struct declaration.
In essence, we currently have this:
```rust
pub(crate) enum ZipFileReader<'a> {
NoReader,
Raw(io::Take<&'a mut dyn Read>),
Stored(Crc32Reader<&'a mut dyn Read>),
#[cfg(feature = …
```
=> remove hardcoded BufRead trait bounds

src/stream/functions.rs, zstd-safe/zstd-sys/build.rs
Hi,
the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the
`wasm32-wasi` target will be removed in the future. It looks like the
shim will also be useful (required?) for `wasm32-wasip2`, so I've included all future `wasm32-wasi*` targets for now.
Thanks!
=> Update `need_wasm_shim` logic for `wasm32-wasip1`

zstd-safe/fuzz/.gitignore, zstd-safe/fuzz/Cargo.toml, zstd-safe/fuzz/fuzz_targets/zstd_fuzzer.rs
This PR creates a `cargo fuzz` directory along with a fuzzing harness. The aim is to include the `zstd-safe` module for fuzzing under OSS-Fuzz.
Fuzzing is essentially a stress testing technique used to uncover bugs in software, and OSS-Fuzz is a free service run by Google that provides continuous fuzzing for important open-source projects. Integrating `zstd-safe` would be beneficial in identifying potential memory corruption issues.
The only requirement for integration at this stage is an email linked to a Google account, which will be used to receive notifications when bugs are detected.
An initial integration has been submitted via https://github.com/google/oss-fuzz/pull/12626, which relies on the fuzzer being hosted upstream. This is the primary objective of this PR.
=> OSS-Fuzz: Add fuzzer for OSS-Fuzz integration

zstd-safe/zstd-sys/Cargo.toml
Cargo.toml says that zstd requires pkg-config "0.3".
This version specification is typically resolved to the most recent pkg-config, but technically, it could be resolved to "0.3.0". However, this version of pkg-config is almost 10 years old, and does not actually work with zstd.
Some projects use a CI-step that checks that selecting minimum versions of all dependencies actually works, and such CI now fails if zstd is in the project crate graph, because of this issue.
We should require a more recent version of pkg-config. I arbitrarily selected "0.3.28", but of course the most recent one will actually be selected for most users. This PR just steps the pkg-config version to 0.3.28. The earliest version that actually compiles is "0.3.7", but it seems strange to explicitly name such an old …
=> Require a more recent version of pkg-config

src/stream/zio/writer.rs
=> Make the buffer size configurable

zstd-safe/src/seekable.rs
Right now `AdvancedSeekable` isn't thread-safe as it contains a raw pointer to `F`. This adds impls to make `AdvancedSeekable` `Send` or `Sync`, if `F` is `Send` or `Sync`.
=> Add Send and Sync markers for AdvancedSeekable

zstd-safe/src/lib.rs
#324 is breaking zstd-safe it seems, submitting a fix if that helps. Thanks
=> fix: update ZSTD_ParamSwitch_e enum in zstd-safe

zstd-safe/src/seekable.rs, zstd-safe/src/tests.rs
Two minor fixes
- The impls on `AdvancedSeekable` had no `cfg` macros, leading to a compilation failure when the `seekable` feature was enabled but not `std`, e.g.:
```text
cargo t -F seekable
Compiling zstd-safe v7.2.3 (/home/rob/misc/zstd-rs/zstd-safe)
Compiling zstd-sys v2.0.14+zstd.1.5.7 (/home/rob/misc/zstd-rs/zstd-safe/zstd-sys)
error[E0412]: cannot find type `AdvancedSeekable` in this scope
--> src/seekable.rs:458:25
|
458 | unsafe impl<F> Send for AdvancedSeekable<'_, F> where F: Send {}
|                         ^^^^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `AdvancedSeekable` in this scope
--> src/seekable.rs:459:25
|
459 | unsafe impl<F> Sync for AdvancedSeekable<'_, F> where F: Sync {}
|                         ^^^^^^^^^^^^^^^^ not found in this scope …
```
=> Add cfg attribute for advanced seekable impls and make seek table creation safe

.github/workflows/linux.yml
Follow-up to #328 
Build and test zstd-safe with different feature combinations in CI.
I only added it to Linux for now since I'm not sure about the others. Let me know if this was meant to be different.
=> Add zstd-safe to CI tests

zstd-safe/zstd-sys/Cargo.toml
I just noticed that `zstd-sys` won't compile due to missing files, if `zstd-safe v7.2.3` is used as dependency and the `seekable` feature is enabled.
This is what I use in my projects `Cargo.toml`
```toml
zstd-safe = { version = "7.2.3", features = ["std", "seekable"] }
```
And this is the error I get 
```
error: failed to run custom build command for `zstd-sys v2.0.14+zstd.1.5.7`
Caused by:
process didn't exit successfully: `/home/rob/misc/zeekstd/target/debug/build/zstd-sys-2b9004de1680cb78/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=ZSTD_SYS_USE_PKG_CONFIG
--- stderr
thread 'main' panicked at /home/rob/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zstd-sys-2.0.14+zstd.1.5.7/build.rs:113:14:
called `Result::unwrap()` on an `Err` value: Os { code: …
```
=> Add seekable format sources to zstd-sys package

zstd-safe/src/lib.rs
This PR exposes the ability to query the frame progression state (`ZSTD_getFrameProgression`) through `CCtx`.
I opted to simply return `ZSTD_frameProgression` directly rather than creating a newtype or anything.
=> enhancement: expose `ZSTD_getFrameProgression` through `CCtx`

src/stream/read/mod.rs, src/stream/write/mod.rs
It seems like it was intended for these to be added in #247. I've been using this implementation and it seems to work fine.
=> Add missing `with_context` constructors
